name: dynamic_gaussians
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cudatoolkit=11.6.2
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.5.0
  - ffmpeg=4.2.2
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnsl=2.0.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.43.2
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - notebook=6.5.2
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=3.0.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.3
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - urllib3=2.0.7
  - wcwidth=0.2.5
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - ansi2html==1.8.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - attrs==23.1.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - click==8.1.7
      - comm==0.1.4
      - configargparse==1.7
      - cycler==0.11.0
      - dash==2.14.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.7.0
      - exceptiongroup==1.1.3
      - fastjsonschema==2.18.1
      - flask==2.2.5
      - fonttools==4.38.0
      - fvcore==0.1.5.post20221221
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - joblib==1.3.2
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - kiwisolver==1.4.5
      - markupsafe==2.0.0
      - matplotlib==3.5.3
      - mistune==3.0.2
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.8
      - notebook-shim==0.2.3
      - open3d==0.16.0
      - opencv-python==4.3.0.36
      - packaging==23.2
      - pandas==1.3.5
      - plotly==5.17.0
      - plyfile==0.9
      - portalocker==2.7.0
      - prometheus-client==0.17.1
      - psutil==5.9.6
      - pyglet==1.2.4
      - pymcubes==0.1.4
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - pytorch3d==0.7.5
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - retrying==1.3.4
      - rtree==1.0.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - send2trash==1.8.2
      - snakeviz==2.2.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - trimesh==4.0.4
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.9
      - yacs==0.1.8
      - zipp==3.15.0