name: dynamic_gaussians
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - torchaudio=0.12.1
  - tqdm=4.65.0
  - pillow=9.4.0
  - pip
  - torchvision=0.13.1
  - pytorch=1.12.1
  - python=3.8
  - cudatoolkit=11.6
  - zeromq
  - ca-certificates
  - jedi
  - pexpect
  - sqlite
  - zlib
  - zstd
  - matplotlib-inline
  - libstdcxx-ng
  - readline
  - ipython_genutils
  - llvm-openmp
  - libsodium
  - pyzmq
  - openssl
  - ld_impl_linux-64
  - libsqlite
  - backports.functools_lru_cache
  - backcall
  - libgcc-ng
  - setuptools
  - decorator
  - xz
  - pygments
  - tk
  - entrypoints
  - pickleshare
  - python-dateutil
  - six
  - _libgcc_mutex
  - wheel
  - traitlets
  - backports
  - _openmp_mutex
  - libffi
  - parso
  - libzlib
  - wcwidth
  - prompt-toolkit
  - ipython
  - ptyprocess
  - tornado
  - ncurses
  - python_abi
  - libnsl
  - libgomp
  - jupyter
  - nbconvert
  - pyparsing
  - mistune
  - pip:
      - fvcore==0.1.5.post20221221
      - iopath==0.1.10
      - ipykernel==6.16.2
      - ipython==7.34.0
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - matplotlib==3.5.3
      - mistune==3.0.2
      - open3d==0.13.0
      - opencv-python==4.3.0.36
      - pandas==1.3.5
      - plotly==5.17.0
      - plyfile==0.9
      - pyglet==1.2.4
      - pymcubes==0.1.4
      - pyyaml==6.0.1
      - rtree==1.0.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - tabulate==0.9.0
      - termcolor==2.3.0
      - trimesh==4.0.4
