##################################################################
# Default settings. Please do not touch this file, which is used to reproduce run_experiments.py
# To change the configuration of a standard training, please use the train.yaml file. 
##################################################################
dataset: ''    # Choose between ShinyBlender, GlossySynthetic, or Real
input_seq: ''  # Path to the directory inside data/, e.g. toaster
output_seq: '' # Path to the directory inside output/<exp>, e.g. toaster_15000
exp_name: ''   # Path to the experiment directory inside output/, e.g. exp1
num_touches: 1   # Number of touches to simulate
iterations: 1  # Number of iterations for the training process
iterations_densify: 1  # Number of iterations for the densification process
ratio_data: 1  # Ratio of the data to use for training
random_selection: False # Randomly select the touches (True/False)

# TEMP ###################################
eval_intermediate: False
###########################################

proximity_mask: False

# Saving
save_eval_data: False  # Save evaluation data (True/False)
eval: True

# Mode
explicit_depth: False   # Enforcing depth Gaussians directly (True/False)
lambda_explicit_depth: 0.1   # Weight for the explicit depth loss

transmittance: False  # Optimise transmittance (True/False)
lambda_transmittance: 0.5  # Weight for the transmittance loss

depth_smoothness: False  # Optimise depth smoothness (True/False)
lambda_depth_smoothness: 0.05  # Weight for the depth smoothness loss

alpha_zero_one: False  # Optimise alpha between 0 and 1 (True/False)
lambda_alpha_zero_one: 0.01  # Weight for the alpha zero one loss